### ISSUE TITLE
Updates needed to PyPI

### ISSUE THREAD

**Issue by wilddeej** [ellisonleao/pyshorteners#100]
**Describe the bug**
The PyPI version of this most excellent package is over a year out-of-date

**To Reproduce**
1. Go to 'https://pypi.org/project/pyshorteners/'
2. Examine the version and date information
3. Compare with this project's latest date/version
4. Notice the large discrepancy

**Expected behavior**
The PyPI version should more closely track the source version

**Screenshots**
N/A

**Desktop (please complete the following information):**
ALL

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ellisonleao** [comment]
sorry about that @wilddeej , the version 1.0 is still under development, that's why i haven't updated the package. I will have plans to do this really soon.
