### ISSUE TITLE
Add support for YOURLS shortener

### ISSUE THREAD

**Issue by wilddeej** [ellisonleao/pyshorteners#104]
**Is your feature request related to a problem? Please describe.**
No problemo.  Well, unless you consider that pyshorteners does not currently support YOURLS.  More information on YOURLS can be found at [https://yourls.org](url)

**Describe the solution you'd like**
Implement the YOURLS shortener solution.  The Python API for YOURLS is available at  [https://github.com/tflink/python-yourls](url)

**Describe alternatives you've considered**
I don't think there is an alternative.  Although this may be outside the defined scope of pyshorteners (as it is arguably not one of the most popular), I think it would still be a good addition in that it provides for a multitude of user-defined shorteners with a single implementation.

**Additional context**
Documentation on the YOURLS Python interface can be found at [http://tflink.github.io/python-yourls/](url)

**Comment by ellisonleao** [comment]
Thanks for the suggestion @wilddeej . Will implement it soon!
