### ISSUE TITLE
bit.ly API v4 

### ISSUE THREAD

**Issue by mark-schulze** [ellisonleao/pyshorteners#125]
**Is your feature request related to a problem? Please describe.**
The bit.ly API v3 will be closed down in 2020, so it would be great to have a future proof solution.

**Describe the solution you'd like**
Especially the authentication has been changed in v4, an api_key has been deprecated and now auth is done via a bearer access_token, which has to be sent in the header with every request.
Would be great if this could be integrated.

**Additional context**

>Authentication
  
 >How you authenticate to the Bitly API has changed with V4. Previously your 
 authentication token would be provided as the access_token query parameter on 
 each request. V4 instead requires that the token be provided as part of the 
 Authorization header on each request.

**Comment by ellisonleao** [comment]
Will include that in the new 1.0 version which is coming up. Thanks for reporting!

**Comment by mark-schulze** [comment]
ok
