### ISSUE TITLE
Update bitly shortener to API v4 and add extra queries

### ISSUE THREAD

**Issue by rkagin** [ellisonleao/pyshorteners#127]
I'm interested in contributing to the pyshorteners library, specifically improving the bitly shortener class.  There were two things I wanted to do:

* Update the class to use the v4 API since v3 will be deprecated in March 2020
* Include additional features to the class such as getting referrer metrics and getting link click dates

It does not appear that anyone is working on this aspect and I would be willing to do all the work to get it done.

**Comment by nachiketdhamankar** [comment]
Have you started working on this? Need a hand?

**Comment by ellisonleao** [comment]
not yet @nachiketdhamankar , feel free to it

**Comment by eutampieri** [comment]
@nachiketdhamankar have you started working on this?

**Comment by rkagin** [comment]
This is currently being worked via https://github.com/ellisonleao/pyshorteners/pull/131 by @jan200101.
