### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/pyshorteners#128]
For now we need:

- pylint
- black formatter

Also, we need to update README file to show to use those for local development

Check how to add pre-commits [here](https://pre-commit.com/#plugins)

**Comment by armonge** [comment]
working on it :+1:

**Comment by armonge** [comment]
working on this

**Comment by alexsolanki** [comment]
@ellisonleao I can work on this if @armonge is not able to.

**Comment by alexsolanki** [comment]
@ellisonleao I can work on this if @armonge is not able to.
