### ISSUE TITLE
Invalid URL fails in specific case

### ISSUE THREAD

**Issue by marcelomaia** [ellisonleao/pyshorteners#145]
**Describe the bug**
function is_valid_url() located in pyshorteners/utils.py fails on this url:
- https://www.shoptime.com.br/produto/7521216/geladeira-refrigerador-electrolux-frost-free-dw42x-380l-inox?DCSext.recom=RR_category_page.rr2-PersonalizedViewedPurchaseInCategory&nm_origem=rec_category_page.rr2-PersonalizedViewedPurchaseInCategory&nm_ranking_rec=4&voltagem=110 volts&opn=AFLSHOP&epar=b2wafiliados&franq=AFL-03-224452&hl=lower

**To Reproduce**
1. shortener = Shortener('Bitly', bitly_token=os.getenv('BITLY_TOKEN'), timeout=20)
    shortener.short(THAT URL ABOVE)

**Expected behavior**
ValueError: Invalid URL

**Desktop (please complete the following information):**
 - OS: linux ubuntu 18.04

**Comment by ellisonleao** [comment]
hey @marcelomaia sorry for the late reply. I will get that fixed in 1.0

**Comment by ellisonleao** [comment]
@marcelomaia 1.0 was just released, i've tested that url and got no errors, can you try on your side?
