### ISSUE TITLE
Update on PyPi

### ISSUE THREAD

**Issue by crablab** [ellisonleao/pyshorteners#146]
:wave:

I've seen a few issues related to the version on PyPi being different from the current code and documentation. 

Is there any progress on getting PyPi updated? Is there anything I can do to help with this? :blush:

**Comment by ellisonleao** [comment]
hey @crablab ! Yeah, current pypi version is outdated and i am still working on the 1.0 version.  There is a [milestone](https://github.com/ellisonleao/pyshorteners/milestone/6) with the remaining tasks to get launched. If you want , you can grab any of those. Any help is very appreciated!

**Comment by ellisonleao** [comment]
@crablab 1.0 is out! make sure to update it on your side

**Comment by crablab** [comment]
Apologies I didn't see the previous comment about the milestones 😭 Would have loved to help. 

But amazing news - thanks for your hard work 🤗
