### ISSUE TITLE
pyshorteners not working with pyinstaller

### ISSUE THREAD

**Issue by dpieski** [ellisonleao/pyshorteners#166]
**Describe the bug**

**To Reproduce**
This is a selected segment that is reproduceable for the error I am getting. 
In the `test.py` file:
```python 
import pyshorteners

def main():
    s = pyshorteners.Shortener()
    print(s.available_shorteners)
    url = s.tinyurl.short('https://google.com')
    print(url)

if __name__ == '__main__':
    main()
```

when running `python test.py`, I get this output:
```powershell
['adfly', 'bitly', 'chilpit', 'clckru', 'cuttly', 'dagd', 'gitio', 'isgd', 'nullpointer', 'osdb', 'owly', 'post', 'qpsru', 'shortcm', 'tinycc', 'tinyurl']
https://tinyurl.com/ydclo84e
```

I then run `pyinstaller -F test.py` and when I run the `test.exe` file, I get:
```
    Traceback (most recent call last):
      File "test.py", line 12, in <module>
      File "test.py", line 5, in main
      File "pyshorteners\__init__.py", line 32, in __init__
      File "importlib\__init__.py", line 127, in import_module
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'pyshorteners.shorteners'
    [13164] Failed to execute script 'test' due to unhandled exception!
```

**Expected behavior**
I get this output:
```powershell
['adfly', 'bitly', 'chilpit', 'clckru', 'cuttly', 'dagd', 'gitio', 'isgd', 'nullpointer', 'osdb', 'owly', 'post', 'qpsru', 'shortcm', 'tinycc', 'tinyurl']
https://tinyurl.com/ydclo84e
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Additional context**
pyshorteners v 1.0.1

**Comment by ellisonleao** [comment]
hey @dpieski i don´t know what pyinstaller is. Can you provide more context on that?

**Comment by dpieski** [comment]
It takes in a python file and produces a Windows executable.
I am guessing there is something wrong with how `pyinstaller` maps out imports when you import pyshorteners. 
I ended up just writing my own functions to get the shortened URL and not using pyshorteners since it was faster than trying to figure this out.

If you want to close, feel free.
