### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by NP-Hardass** [ellisonleao/pyshorteners#21]
Hello,
I've noticed that you do not have tags for the last 3 versions, and would like to request that the tags be added.
0.2.9 9b5b1a49c9c341a760d78f498dbb8535753cf462
0.2.10 f1efdde6e58d01e64effb310cdfdbea91d272854
0.3 69a49a5ada371f42aafefdf72034b90f28bcde0d

Thank you in advance.

**Comment by ellisonleao** [comment]
thanks for the remindal! will do it asap

**Comment by ellisonleao** [comment]
hey @NP-Hardass , the releases are done. Thanks

https://github.com/ellisonleao/pyshorteners/releases

**Comment by NP-Hardass** [comment]
Thank you very much again.
