### ISSUE TITLE
goo.gl now requires OAUTH 2.0 tokens and/or API keys to function and thus is broken

### ISSUE THREAD

**Issue by NP-Hardass** [ellisonleao/pyshorteners#23]
https://developers.google.com/url-shortener/v1/getting_started

"Every request your application sends to the Google URL Shortener API needs to identify your application to Google. There are two ways to identify your application: using an OAuth 2.0 token (which also authorizes the request) and/or using the application's API key. Here's how to determine which of those options to use:

If the request requires authorization (such as a request for an individual's private data), then the application must provide an OAuth 2.0 token with the request. The application may also provide the API key, but it doesn't have to.
If the request doesn't require authorization (such as a request for public data), then the application must provide either the API key or an OAuth 2.0 token, or both—whatever option is most convenient for you."

**Comment by ellisonleao** [comment]
Nice, i will make the chances to the older  version since i am working in a new version (1.0) with a completely new design for the shorteners.

Thanks for the feedback!

**Comment by ellisonleao** [comment]
@NP-Hardass i've implemented only the api_key param for now, since the oauth requires a effort which is not required for this lib.  Thanks again!

**Comment by NP-Hardass** [comment]
Terrific. Thank you.
