### ISSUE TITLE
warning: no files found matching 'README.md'

### ISSUE THREAD

**Issue by rochacbruno** [ellisonleao/pyshorteners#26]
Small issue, there is a warning on setup, maybe MANIFEST.in is not including README.md in the distribution (maybe because MANIFEST is failing to include README.rst in its first line.

```
  Running setup.py install for pyshorteners
    Skipping installation of /home/rochacbruno/.virtualenvs/quokka/lib/python2.7/site-packages/pyshorteners/__init__.py (namespace package)
    
    warning: no files found matching 'README.md'
    Installing /home/rochacbruno/.virtualenvs/quokka/lib/python2.7/site-packages/pyshorteners-0.4.1-py2.7-nspkg.pth
```

**Comment by rochacbruno** [comment]
https://github.com/ellisonleao/pyshorteners/blob/master/MANIFEST.in#L1

**Comment by ellisonleao** [comment]
Forgot about the Manifest! Thanks @rochacbruno . Did you try to install the current master branch, right?

**Comment by ellisonleao** [comment]
Fixed on https://github.com/ellisonleao/pyshorteners/commit/617834f466c418b94fb2255c0f8020005c600806

md file added. New version `0.4.2` released
