### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by miqro** [ellisonleao/pyshorteners#31]
Hey,

I installed pyshorteners via pip, and says it installed fine.. but when i try to import 'from pyshorteners import Shortener' and run the code, i get error:
http://i.imgur.com/UXCtqgq.png

**Comment by ellisonleao** [comment]
Hey @miqro , that new import is for the `0.5` version which is not on pypi yet. 

For now you can use

    from pyshorteners.shorteners import Shortener

**Comment by ellisonleao** [comment]
Hey @miqro i just updated a new version on pypi. You will need to update it in order to work.

    pip install pyshorteners -U

Please let me know if it goes well

**Comment by rahiel** [comment]
Hello, I had the same problem with the current version of the package on pypi.  
`from pyshorteners import Shortener` gives an `ImportError: cannot import name Shortener` but 
`from pyshorteners.shorteners import Shortener` works.

So the examples from the readme are broken.
