### ISSUE TITLE
ImportError: cannot import name Shortener

### ISSUE THREAD

**Issue by rahiel** [ellisonleao/pyshorteners#32]
I get an ImportError with the current version on pypi:
`from pyshorteners import Shortener` gives an `ImportError: cannot import name Shortener` but 
`from pyshorteners.shorteners import Shortener` works.

So the examples from the readme also don't work now.

**Comment by ellisonleao** [comment]
Hey @rahiel what version are you using? `pip freeze |  grep pyshorteners`

**Comment by rahiel** [comment]
Output is: `pyshorteners==0.5.5`

**Comment by ellisonleao** [comment]
@rahiel please update to the new version (0.5.6) and try again

```
pip install pyshorteners -U
```

just tested here and it was working

**Comment by rahiel** [comment]
It's fixed, thanks!
