### ISSUE TITLE
Can's install using pip

### ISSUE THREAD

**Issue by roloyar** [ellisonleao/pyshorteners#33]
Hey guys! Tried installing today with "pip install pyshorteners", returned this:

$ pip install pyshorteners
Downloading/unpacking pyshorteners
  Could not find any downloads that satisfy the requirement pyshorteners
Cleaning up...
No distributions at all found for pyshorteners
Storing debug log for failure in /home/******/.pip/pip.log

Did successfully install via downloading and running python setup.py install

**Comment by ellisonleao** [comment]
Please read #34

**Comment by roloyar** [comment]
Oh, got it, thank you!

**Comment by ellisonleao** [comment]
@roloyar just update it. Please try again :)
