### ISSUE TITLE
Timeout Argument

### ISSUE THREAD

**Issue by CBickel87** [ellisonleao/pyshorteners#37]
Is there a good way to set a timeout argument? I'm currently using the TinyURL Shortener and I'm running into tinyurl not being able to respond in time. I attempted to set a timeout argument, but it seems to get overridden. The specific exception I'm receiving is below.

HTTPConnectionPool(host='tinyurl.com', port=80): Read timed out. (read timeout=0.5)

I see there is timeout default set in _init_.py but I was hoping there was a good process for passing that parameter within my script. Thank you.

**Comment by ellisonleao** [comment]
Hey @CBickel87 can you paste your code so i can reproduce it here? also what version are you using?

**Comment by CBickel87** [comment]
Certainly - my apologies for not posting it with my initial inquiry.
My code is located below. I'm using Python version 3.5.0

https://github.com/CBickel87/CarScraping/blob/master/scrapeAutoTrader.py 

I've noticed if I change the timeout kwargs to a higher value (located in 
Python35\Lib\site-packages\pyshorteners\shorteners\ \_init_.py) then the requests to TinyURL seem to have enough time to respond.

The timeout parameter that I'm changing, that I've had success with, is located in the _init_.py file, that I mentioned above, within the short(self, url): method. 

        if url:
            if not self.kwargs.get('timeout'):
                self.kwargs['timeout'] = 0.5

My intention is to pass my own timeout value from within my script. If that is possible, where would I place the timeout argument? Thank you

**Comment by ZhukovAlexander** [comment]
@CBickel87 , you can pass the `timeout` argument to the `__init__` method. So, changing [this line](https://github.com/ellisonleao/pyshorteners/blob/master/pyshorteners/shorteners/base.py#L22) to this
```python
    shortener = Shortener('TinyurlShortener', timeout=9000)
```
will solve your issue.

**Comment by CBickel87** [comment]
@ZhukovAlexander , Thank you very much. This was exactly what I was looking for, but I just couldn't figure out where this argument would go. It works well and my curiosity is satisfied.

**Comment by ellisonleao** [comment]
Yes @CBickel87 , @ZhukovAlexander got exactly what i was going to tell you. Thanks for that! Closing the issue :+1:
