### ISSUE TITLE
i get bad handshake: Error when i try to run it 

### ISSUE THREAD

**Issue by jalsco** [ellisonleao/pyshorteners#39]
<type 'exceptions.Exception'> 

bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

Am running on:  python2.7 

Just using the example with default (google shortner)  - i.e. 

shortener = Shortener('GoogleShortener', api_key=goog_api_key)
 print "My short url is {}".format(shortener.short('http://stackoverflow.com'))

**Comment by jalsco** [comment]
File "shorter.py", line 10, in <module>
    print "My short url is {}".format(shortener.short(url))
  File "/usr/local/lib/python2.7/dist-packages/pyshorteners/shorteners/__init__.py", line 82, in short
    self.shorten = self._class(**self.kwargs).short(url)
  File "/usr/local/lib/python2.7/dist-packages/pyshorteners/shorteners/googl.py", line 25, in short
    response = self._post(url, data=params, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/pyshorteners/shorteners/base.py", line 24, in _post
    timeout=self.kwargs['timeout'])
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

**Comment by jalsco** [comment]
How to fix that ???  :)

**Comment by jalsco** [comment]
is there some way to specify:   verify=False     ??   (for the requests module)

**Comment by ellisonleao** [comment]
hey @jalsco can you show what python version and openSSL are you using?
i've tested your example using

```
OpenSSL 0.9.8zg 14 July 2015
Python 2.7.10
```

and  everything went well

**Comment by jalsco** [comment]
Thank you for your very fast reply :)  

Python 2.7.6

 openssl version -a
OpenSSL 1.0.1f 6 Jan 2014
built on: Thu Jun 11 15:28:12 UTC 2015
platform: debian-amd64

**Comment by jalsco** [comment]
still getting it ... 

<type 'exceptions.Exception'> bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

when i have seem similar - in the past - I have added this option onto the requests.get call   "verify=certifi.old_where()"   or "verify=certifi.where()" or even "verify=false"  

But  in this case it is all wrapped up in Shortener()  so I cannot easily add the verify= option...

Your thoughts  ?

**Comment by ellisonleao** [comment]
Yeah, i've searched for this verify param, however i still think it's a openssl version issue. Can you try to upgrade it along with your python version (2.7.10) and try again, please?

**Comment by jalsco** [comment]
I can't upgrade the server to 2.7.10 because there are many Python systems that run on it - in production -- this new functionality in one system - cannot dictate such a massive change in server environment. I believe there are items in several of those systems that will not run fully on 2.7.10 without some major updating.. OpenSSL is on the latest supported level for my Ubuntu 14.04

**Comment by jalsco** [comment]
Could you possibly add (optional) the verify= param to Shortener() - and then pass thru, to the requests module, whatever "verify=" was entered on Shortener() .. I am just shortening a URL with Google . It is not sensitive or secure info . I my case I will be happy using verify=false  but I will try the other verify= options first.

**Comment by jalsco** [comment]
Sorry I closed it by mistake

**Comment by ellisonleao** [comment]
hey @jalsco can you try test with the latest code? I haven't added it on pip yet, so you will need to test locally for now. If your test goes ok, please let me know and i will update the version

```bash
git clone https://github.com/ellisonleao/pyshorteners.git
cd pyshorteners
python setup.py develop
```

Make sure you are using `0.5.9` version

```python
from pyshorteners import __version___
print __version___
# output should be '0.5.9'
```

**Comment by jalsco** [comment]
ok - try it

**Comment by jalsco** [comment]
ok i tried - YES it works :)  it gets past the SSL handshake problem :)) 

Some other comments: 
1. I tried like you said but  I could  not get the __version__ part to work , so I just commented that out , and tried it anyway .. I was getting  "   from pyshorteners import __version___
  ImportError: cannot import name __version___  "   --  It is probably something I did wrong . 

2.   I run the code  with verify=False and first I get message -  that I expect to get - :)  - This means that the requests module is using "verify=false" so I know is using the new version of Shortener(). 

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

3. Then I get back from google :  this is my problem - means that shortener() is  sending the request to google  --  maybe i got some problem with the google api key i set up - but it seems Shortener() is now working THANK YOU THANK :) 

<type 'exceptions.Exception'> There was an error shortening this url - {
"error": {
"errors": [
{
"domain": "usageLimits",
"reason": "accessNotConfigured",
"message": "Access Not Configured. The API (URL Shortener API) is not enabled for your project. Please use the Google Developers Console to update your configuration.",
"extendedHelp": "https://console.developers.google.com"
}
 ],
 "code": 403,"message": "Access Not Configured. The API (URL Shortener API) is not enabled for your project. Please use the Google Developers Console to update your configuration."
 }
}

**Comment by jalsco** [comment]
i fixed my - api key - enabled shorten-url - in google console - and now it is working perfectly by using verify=False   :) :)

**Comment by jalsco** [comment]
http://goo.gl/FvOM

**Comment by ellisonleao** [comment]
Nice! Closing then
