### ISSUE TITLE
add wp-a.co integration

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/pyshorteners#40]
website: http://wp-a.co

API: `http://wp-a.co/api/?url={{LINK}}&customshort={{CUSTOM ALIAS}}&method={{'http' or 'json''}}`

**Comment by vmesel** [comment]
Thanks @ellisonleao !

**Comment by ellisonleao** [comment]
wp-a.co was added on `pyshorteners==0.6.0` You can update it now.
