### ISSUE TITLE
List of all supported shorteners

### ISSUE THREAD

**Issue by Oire** [ellisonleao/pyshorteners#45]
I'm very impressed by this library, thanks @ellisonleao! However, I would like to have a possibility to get a list of all supported URL shorteners to output it to my app, so a user could easily select a shortener he/she wants.

**Comment by ellisonleao** [comment]
There is a way right now, but its not that straightforward.

```python
from pyshorteners import Shorteners

s = dir(Shorteners)
s = [i for i in s if '__' not in i]
print s

# output
['ADFLY',
 'AWSM',
 'BITLY',
 'CLCKRU',
 'GOOGLE',
 'ISGD',
 'OSDB',
 'OWLY',
 'QPSRU',
 'QRCX',
 'READABILITY',
 'SENTALA',
 'SIMPLE',
 'TINYURL',
 'WPACO']
```
