### ISSUE TITLE
Making Python3 certificate verification work using PoolManager

### ISSUE THREAD

**Issue by MrBillium** [ellisonleao/pyshorteners#52]
Running Python 3.4  & goo.gl and  was only able to get the sample going with Verify=False
The output warning had a helpful link in it 
_Adding certificate verification is strongly advised. See:_ 
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

The linked page shows me how to enable checks with  a poolmanager:

`http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED', # Force certificate check.
    ca_certs=certifi.where(),  # Path to the Certifi bundle.
)`

How do I  use this with pyshortener?

Thanks

Bill

**Comment by ellisonleao** [comment]
Thanks for the heads up @MrBillium . I am planning to move the code to python3 only, but due my work, that could take some time. But i am taking this issue as priority for when things start.

**Comment by ellisonleao** [comment]
Just added a `verify` flag on the current 1.0 version which will go live shortly. Please look out for the docs when its available. Thanks
