### ISSUE TITLE
[Enhancement] Needs more URL shortening services

### ISSUE THREAD

**Issue by SillySam** [ellisonleao/pyshorteners#61]
With some URL shortening services shutting down, there is a need for more functional shortening services within the project.

To get started:
- Research services that have a get/post request API
- Check the [documentation](https://github.com/ellisonleao/pyshorteners#creating-your-own-shortener) to incorporate your new service

**Comment by sdushantha** [comment]
Should we add the git.io shortener?

**Comment by SillySam** [comment]
Sure thing! It looks quite nice.

**Comment by sdushantha** [comment]
If you take a look at this [repo](https://github.com/sdushantha/gitio) , you could use that method. Right?

**Comment by SillySam** [comment]
It looks pretty good, go at it!

**Comment by hidalgopl** [comment]
Cool! If I can help with anything, just give me a shout!

**Comment by ellisonleao** [comment]
@hidalgopl thanks! Would be good to know any new APIs that can be added. If you have any suggestions i am all ears

**Comment by ellisonleao** [comment]
@SillySam do you have new  APIs suggestions ?

**Comment by SillySam** [comment]
@ellisonleao haven't been very active recently sorry. I haven't been on the search recently but you may be able to find something.
