### ISSUE TITLE
Remove or update RTD site

### ISSUE THREAD

**Issue by Doezer** [ellisonleao/pyshorteners#64]
The RTD site has wrong instructions and is pretty high in google results
https://readthedocs.org/projects/pyshorteners/

**Comment by ellisonleao** [comment]
hey @Doezer thanks for raising this! will update it ASAP

**Comment by ellisonleao** [comment]
Just removed the RTD entry. The docs will live only on http://ellisonleao.github.io/pyshorteners/ now.
