### ISSUE TITLE
Custom timeout kwarg on Shortener class

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/pyshorteners#9]
Create a timeout argument on Shortener class for preventing possible requests timeout errors

**Comment by oakkitten** [comment]
@ellisonleao so uh is there a way to provide timeout arguments now?

**Comment by ellisonleao** [comment]
@oakkitten actually not yet.  I will reopen this one and make the changes. thanks for the reminding.

**Comment by ellisonleao** [comment]
@oakkitten You can now pass a `timeout` kwarg when instantiating a new `Shortener` class. Example:

```python
from pyshorteners import Shortener
s = Shortener('TinyurlShortener', timeout=3)
print s.short('http://www.test.com')
```

**Comment by oakkitten** [comment]
great, thanks!
